---
apiVersion: v1
kind: Service
metadata:
  name: hive-service
  namespace: metastore
spec:
  type: NodePort
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
      nodePort: 30083
    - name: "10000"
      port: 10000
      targetPort: 10000
      nodePort: 30011
  selector:
    app: hive-metastore
---
