---
apiVersion: v1
kind: Service
metadata:
  name: hive-service
  namespace: metastore
spec:
  type: NodePort
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
      nodePort: 30083
  selector:
    app: hive
---
